name: Java with Maven Automated Testing Pipeline

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  selenium-test :
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'adopt'
    
    - name: Run Selenium tests
      run: |
        cd selenium-test
        mvn clean test   
    # - name: Save test reports as artifacts
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: test-reports
    #     path: ./nightwatch-test
    # - name: Archive test reports
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: test-reports
    #     path: selenium-test/reports
