name: Java with Maven Automated Testing Pipeline

on:
  push:
    branches: [ "main" ]
    paths:
    - 'selenium-test/*'
  pull_request:
    branches: [ "main" ]

jobs:
  selenium-test :
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: |
        mvn -B package --file selenium-test/pom.xml
