
name: Rest Asured Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  rest_assured_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '11' # or the version you need for your Rest Assured tests

    - name: Install Maven
      run: |
        sudo apt-get install maven -y

    - name: Build and test project
      run: mvn clean test

    # Optionally, if you want to upload test reports as artifacts
    - name: Archive test reports
      uses: actions/upload-artifact@v2
      with:
        name: rest-assured-test-reports
        path: target/surefire-reports

