# This is a basic workflow to help you get started with Actions

name: Automated Testing Pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    paths:
    - 'nightwatch-test/*'
  pull_request:
    branches: [ "main" ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job 
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Nightwatch Test Started!
        
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Change Directory
        run: cd nightwatch-test

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Install dependencies and run Nightwatch Tests
        run: |
          cd nightwatch-test
          npm install
          npm run nightwatch
